create database superstore_db; /* i created the database for the tables in the database*/

/* imported the tables which are in csv format inside the above SQL database*/
use superstore_db;

select * from orderdetails;

ALTER TABLE orderdetails
Drop COLUMN SALES;

UPDATE orderdetails
SET OrderDates=cast(OrderDate as date);

DESC orderdetails;

# BASIC QUESTIONS

# 1. 
# Question: Select the maximum quantity of goods ordered and the number of all transactions made.;

SELECT MAX(quantity), count(*)
FROM  orderdetails;

# 2. 
-- Find the unique products in all the transaction.;
SELECT DISTINCT PRODUCTiD, QUANTITY
FROM orderdetails
ORDER BY QUANTITY DESC;

# 3. 
-- Find the Unique properties.;
SELECT DISTINCT PROPERTYID
FROM ORDERDETAILS;

-- Moving forward- GROUP BY 

# 4. FIND THE PRODUCT CATEGORY THAT HAS MAXIMUM PRODUCT
SELECT PRODUCTCATEGORY, count(*) as count
FROM products
GROUP BY PRODUCTCATEGORY
ORDER BY count DESC;

# 5. FIND THE STATE WHERE MOST STORES ARE PRESENT
SELECT PROPERTYSTATE, count(*) as count
FROM PROPERTYINFO
GROUP BY PROPERTYSTATE
ORDER BY count DESC;

# 6. FIND THE TOP 5 PRODUCT IDS THAT DID MAXIMUM SALES IN TERMS OF QUANTITY
SELECT PRODUCTID, SUM(QUANTITY) QUANTITY_SOLD
FROM ORDERDETAILS
GROUP BY PRODUCTID
ORDER BY 2 DESC
LIMIT 5;

# 7. SIMILARLY, FIND THE TOP 5  PROPERTY ID'S THAT DID THE MAXIMUM QUANTITY.
SELECT PROPERTYID, SUM(QUANTITY) QUANTITY_SOLD
FROM ORDERDETAILS
GROUP BY PROPERTYID
ORDER BY 2 DESC
LIMIT 5;


-- INTERMEDIATE - JOINS AND GROUP BY 

# 8.	FIND THE TOP 5 PRODUCT NAMES THAT DID MAXIMUM SALES IN TERMS OF QUANTITY

SELECT P.PRODUCTNAME, SUM(O.QUANTITY) QUANTITY_SOLD
FROM ORDERDETAILS O
LEFT JOIN PRODUCTS P
on O.PRODUCTID = P.PRODUCTID
GROUP BY O.PRODUCTID
ORDER BY 2 DESC
LIMIT 5;

# 9.	THE TOP 5 PRODUCTS THAT DID THE MAXIMUM SALES
SELECT *
FROM;

SELECT P.PRODUCTNAME, SUM(O.QUANTITY * P.PRICE) SALES_AMOUNT
FROM ORDERDETAILS O
LEFT JOIN PRODUCTS P
on O.PRODUCTID = P.PRODUCTID
GROUP BY O.PRODUCTID
ORDER BY 2 DESC
LIMIT 5;

# 10.	FIND THE TOP 5 CITIES THAT DO MAXIMUM SALES
SELECT PO.PROPERTYCITY, SUM(O.QUANTITY * P.PRICE) SALES_AMOUNT
FROM ORDERDETAILS O
LEFT JOIN PRODUCTS P
on O.PRODUCTID = P.PRODUCTID
LEFT JOIN PROPERTYINFO PO
ON O.PROPERTYID = PO.`Prop ID`
GROUP BY PO.PROPERTYCITY
ORDER BY 2 DESC
LIMIT 5;

-- Advanced - Joins and Group By

# 11. Find the top 5 products in each Cities

SELECT PO.PROPERTYCITY, P.PRODUCTNAME, SUM(O.QUANTITY * P.PRICE) SALES_AMOUNT
FROM ORDERDETAILS O
LEFT JOIN PRODUCTS P
on O.PRODUCTID = P.PRODUCTID
LEFT JOIN PROPERTYINFO PO
ON O.PROPERTYID = PO.`Prop ID`
GROUP BY PO.PROPERTYCITY
ORDER BY 3 DESC;